# Generated by Django 5.0.3 on 2024-04-14 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_person_description_person_main_work_areas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='main_work_areas',
            new_name='specialization',
        ),
    ]
