# Generated by Django 5.0.3 on 2024-04-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_rename_main_work_areas_person_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='programming_language',
            field=models.TextField(blank=True, choices=[('python', 'Python'), ('java', 'Java'), ('cpp', 'C++'), ('csharp', 'C#')], null=True),
        ),
    ]
