# Generated by Django 5.0.3 on 2024-04-17 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_person_experience_person_programming_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
    ]
