# Generated by Django 5.0.3 on 2024-05-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0006_alter_person_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='person',
            name='specialization',
        ),
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='person',
            name='programming_language',
            field=models.TextField(blank=True, choices=[('python', 'Python'), ('java', 'Java'), ('cpp', 'C++'), ('csharp', 'C#')], null=True, verbose_name='Язык программирования'),
        ),
    ]
