# Generated by Django 5.0.3 on 2024-05-15 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0007_remove_person_experience_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-date_joined']},
        ),
    ]
