# Generated by Django 5.0.3 on 2024-06-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0009_person_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='discord_url',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Discord'),
        ),
        migrations.AddField(
            model_name='person',
            name='github_url',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Github'),
        ),
        migrations.AddField(
            model_name='person',
            name='tg_url',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram'),
        ),
    ]
