# Generated by Django 5.0.3 on 2024-06-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0010_person_discord_url_person_github_url_person_tg_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='team',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Команда'),
        ),
        migrations.AddField(
            model_name='person',
            name='year',
            field=models.IntegerField(blank=True, max_length=4, null=True, verbose_name='Год обучения'),
        ),
    ]
