# Generated by Django 5.0.3 on 2024-06-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0011_person_team_person_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile_background',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фон профиля'),
        ),
    ]
