# Generated by Django 5.0.3 on 2024-06-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0017_alter_person_profile_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='team',
        ),
        migrations.RemoveField(
            model_name='person',
            name='group',
        ),
        migrations.AddField(
            model_name='person',
            name='group',
            field=models.TextField(blank=True, choices=[('AT-01', 'AT-01'), ('AT-02', 'AT-02'), ('AT-03', 'AT-03'), ('AT-04', 'AT-04'), ('AT-05', 'AT-05'), ('AT-06', 'AT-06'), ('AT-07', 'AT-07'), ('AT-08', 'AT-08'), ('AT-09', 'AT-09')], verbose_name='Группa'),
        ),
    ]
