# Generated by Django 5.0.3 on 2024-06-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0017_alter_person_profile_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_background',
            field=models.CharField(blank=True, choices=[('0da2408752e4e15427f68d12ab1e3ad9.jpg', '0da2408752e4e15427f68d12ab1e3ad9.jpg'), ('120ad05d31ed0df507b329994f600ab9.jpg', '120ad05d31ed0df507b329994f600ab9.jpg'), ('1a9cc4ae5e7f7a5e097ae9ded89d37e8.jpg', '1a9cc4ae5e7f7a5e097ae9ded89d37e8.jpg'), ('2be65e7b92082739e53ce04f78a0b1da.jpg', '2be65e7b92082739e53ce04f78a0b1da.jpg'), ('2edce7c690cb2756a26b7483bb4aeafd.jpg', '2edce7c690cb2756a26b7483bb4aeafd.jpg'), ('2fb373825ad3ff81428db30346bce0a7.jpg', '2fb373825ad3ff81428db30346bce0a7.jpg'), ('45efbd5562cd67cd631f63fba563fc1f.jpg', '45efbd5562cd67cd631f63fba563fc1f.jpg'), ('48bfc8ed804bf4945c945970df960115.jpg', '48bfc8ed804bf4945c945970df960115.jpg'), ('51f20bc96429f74ddc9bba44ea584bcf.jpg', '51f20bc96429f74ddc9bba44ea584bcf.jpg'), ('53fabe8a3ae68b3bd4d09661e627ed34.jpg', '53fabe8a3ae68b3bd4d09661e627ed34.jpg'), ('5e02b553c9bdc9651ea29362c3612937.jpg', '5e02b553c9bdc9651ea29362c3612937.jpg'), ('64ce82f4e7f6d1383fd01cc3be143382.jpg', '64ce82f4e7f6d1383fd01cc3be143382.jpg'), ('64ce82f4e7f6d1383fd01cc3be1433821.jpg', '64ce82f4e7f6d1383fd01cc3be1433821.jpg'), ('7c581985843f99a031bb089d9dddddb2.jpg', '7c581985843f99a031bb089d9dddddb2.jpg'), ('8f39860ced3fb6f5c17f30965a65cc3d.jpg', '8f39860ced3fb6f5c17f30965a65cc3d.jpg'), ('8f39860ced3fb6f5c17f30965a65cc3d1.jpg', '8f39860ced3fb6f5c17f30965a65cc3d1.jpg'), ('8f39860ced3fb6f5c17f30965a65cc3d2.jpg', '8f39860ced3fb6f5c17f30965a65cc3d2.jpg'), ('99bc54da12675b220946ff6e0ae33133.jpg', '99bc54da12675b220946ff6e0ae33133.jpg'), ('a1f0a9682e852ef60e26a4151e29fd6d.jpg', 'a1f0a9682e852ef60e26a4151e29fd6d.jpg'), ('a2d1dc0aec70f367fd6c6b11246337dc.jpg', 'a2d1dc0aec70f367fd6c6b11246337dc.jpg'), ('a2d1dc0aec70f367fd6c6b11246337dc1.jpg', 'a2d1dc0aec70f367fd6c6b11246337dc1.jpg'), ('a2d1dc0aec70f367fd6c6b11246337dc2.jpg', 'a2d1dc0aec70f367fd6c6b11246337dc2.jpg'), ('aa6e7ea1eceff76bb49436f12b24d079.jpg', 'aa6e7ea1eceff76bb49436f12b24d079.jpg'), ('ac704444443aa1a680195304ca46d230.jpg', 'ac704444443aa1a680195304ca46d230.jpg'), ('b2d399f8e6bcd663e3e4e38e6af12cbb.jpg', 'b2d399f8e6bcd663e3e4e38e6af12cbb.jpg'), ('bbcafc2a4cefcecc98c2a941165c444b.jpg', 'bbcafc2a4cefcecc98c2a941165c444b.jpg'), ('d5798b6e8dea393dc1dbaca37242baee.jpg', 'd5798b6e8dea393dc1dbaca37242baee.jpg'), ('d5798b6e8dea393dc1dbaca37242baee1.jpg', 'd5798b6e8dea393dc1dbaca37242baee1.jpg'), ('dd640ed38d97e7a7e295b94663b68985.jpg', 'dd640ed38d97e7a7e295b94663b68985.jpg'), ('e2c87797cc66fcf3696a18d79eca425c.jpg', 'e2c87797cc66fcf3696a18d79eca425c.jpg'), ('e2c87797cc66fcf3696a18d79eca425c1.jpg', 'e2c87797cc66fcf3696a18d79eca425c1.jpg'), ('e89d04e194a836299f90e87a750dd2e5.jpg', 'e89d04e194a836299f90e87a750dd2e5.jpg'), ('e89d04e194a836299f90e87a750dd2e51.jpg', 'e89d04e194a836299f90e87a750dd2e51.jpg'), ('f1da4686128681.5d909dad51629.jpg', 'f1da4686128681.5d909dad51629.jpg'), ('fc6791c0cda422522d9efaa1cd967bb9.jpg', 'fc6791c0cda422522d9efaa1cd967bb9.jpg'), ('ff68c63c6faccd166612f7b6f22f6354.jpg', 'ff68c63c6faccd166612f7b6f22f6354.jpg'), ('profile_background.jpg', 'profile_background.jpg')], default='profile_background.jpg', max_length=255, null=True, verbose_name='Фон профиля'),
        ),
    ]
