# Generated by Django 5.0.3 on 2024-06-16 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0018_alter_person_profile_background'),
        ('persons', '0018_remove_person_team_remove_person_group_person_group'),
    ]

    operations = [
    ]
