# Generated by Django 5.0.3 on 2024-06-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0019_merge_20240616_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='group',
            field=models.TextField(blank=True, choices=[], verbose_name='Группa'),
        ),
    ]
