# Generated by Django 5.0.3 on 2024-06-16 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0020_alter_person_group'),
        ('persons', '0021_alter_person_group'),
    ]

    operations = [
    ]
