# Generated by Django 5.0.3 on 2024-06-17 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0023_alter_person_group_alter_person_profile_background'),
        ('persons', '0023_person_role'),
    ]

    operations = [
    ]
