# Generated by Django 5.0.3 on 2024-06-18 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0029_alter_person_group_alter_person_profile_background'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
