# Generated by Django 5.0.3 on 2024-04-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='authors',
            field=models.ManyToManyField(related_name='projects', to='persons.person'),
        ),
    ]
