# Generated by Django 5.0.3 on 2024-04-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_authors_remove_project_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.TextField(blank=True, choices=[('web', 'Web'), ('mobile', 'Mobile'), ('desktop', 'Desktop'), ('game', 'Game')], null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='programming_language',
            field=models.TextField(blank=True, choices=[('python', 'Python'), ('java', 'Java'), ('cpp', 'C++'), ('csharp', 'C#')], null=True),
        ),
    ]
