# Generated by Django 5.0.3 on 2024-05-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_category_project_programming_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.TextField(blank=True, choices=[('web', 'Web'), ('mobile', 'Mobile'), ('desktop', 'Desktop'), ('game', 'Game'), ('ml', 'Machine Learning'), ('ds', 'Data Science'), ('cv', 'Computer Vision')], null=True),
        ),
    ]
