# Generated by Django 5.0.3 on 2024-06-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.AlterField(
            model_name='project',
            name='programming_language',
            field=models.TextField(blank=True, choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('Java', 'Java'), ('Cpp', 'C++'), ('Csharp', 'C#'), ('Ruby', 'Ruby'), ('Golang', 'Golang'), ('Scala', 'Scala')], null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='projects.tag', verbose_name='Теги'),
        ),
    ]
