# Generated by Django 5.0.3 on 2024-06-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_tag_remove_project_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='grade',
            field=models.IntegerField(default=0, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='projects.tag', verbose_name='Теги'),
        ),
    ]
