# Generated by Django 5.0.3 on 2024-06-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link_on_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на гитхаб'),
        ),
    ]
